appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HJab6Ll5MqxKf8RQ3f8oMSfigT1noX+hdADE3vLZDtVo93O8cgaLOjd9rax/reXqmrWLAij4lktWcxS3Ha5I9MD1JTcAYMZ3f8U9UvygLHzJR/eer5q2JVLKvgMvnH0ZRaXBrwATm58N+E6jrUf+x8xFXVeykyUkA9s74d7XjZLlhta925GxezI+l1pEDee2uR0SqTr1BEvVymr6EZvtdoneu15cYICPvqSb805Oa25sPB3ozbIz0zDItou+9NiqtjRJofyHmlxy6m+IO0cSt8K7Q/PCsqc/AniiO3ehgL4B7I4wYOgQBnXJkVe71ObpYzfAnNiRKGYWEy6Wiaf8GRrtE537Hby5To0kOJgvZ4ZIHxfh+W6GhUNl4LjDwTYPN+Sich5PTbZNgqYaXQnOekhPAFjbd7dIG/OkpeDzhcL3W8+rIyyjH9p9Edha/9xkSgMw7oio+fAuSWGUOp8tSKOZuH1MvYwsFFpaudRXhoJsXroFFUKRGftj7ggu3n6pCu297dXDJ8YqX7AhflInW0VYSHptTagU4X9xxIV6vXkBM5NAtjig7yCAETlWRSUkmH0ZFGoIjHD1CK3Z36cSfJvb4Ay0Eur2VglZY3bz0+80xF/9UmuxHwF4YcGqEZQWDQdUTAwAicaKDPwfW9d831NnuoNZioupdfOmL3PK8S0=}
bot:
  automerge: true
